## via Aditya░Shakya░@adi1090x @ https=//github.com/adi1090x/polybar-themes

[colors]
##002B36 #586E75 #839496 #EEE8D5 #B58900 #DC322F #6C71C4 #2AA198 #B8D8D6
##073642 #657B83 #93A1A1 #FDF6E3 #CB4B16 #D33682 #268bC2 #859900 #C5E7E5

; --| main colors |------------------------------------------------------------
#ARGB color (e.g. #f00, #ff992a, #dbff10ff)
background =    #C5E7E5
background-alt =#000000ff
foreground =    #042623
primary =       #CB4B16
secondary =     #B8D8D6
alert =         #D33682
disabled =      #93A1A1
tray0 =         #707000
base03 =        #002B36
base02 =        #073642
base01 =        #586E75
base00 =        #657B83
base0 =         #839496
base1 =         #93A1A1
base2 =         #EEE8D5
base3 =         #FDF6E3
yellow =       #B58900
orange =       #CB4B16
red =          #DC322F
magenta =      #D33682
violet =       #6C71C4
blue =         #268bC2
cyan =         #2AA198
green =        #859900

active =        #B8D8D6
inactive =      #C5E7E5
