#┌──────────────────────────────────────────────────────────────────────────────-----┐
#│░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█░█░█▀▀░█▀▀░█▀▄░░░█▄█░█▀█░█▀▄░█░█░█░░░█▀▀░█▀▀ │
#│░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░█░▀▀█░█▀▀░█▀▄░░░█░█░█░█░█░█░█░█░█░░░█▀▀░▀▀█ │
#│░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀▀░▀▀▀░▀▀▀░▀░▀░░░▀░▀░▀▀▀░▀▀░░▀▀▀░▀▀▀░▀▀▀░▀▀▀ │
#│░Created░By░Aditya░Shakya░@adi1090x░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░│
#└──────────────────────────────────────────────────────────────────────────────-----┘
#via Aditya░Shakya░@adi1090x @ https://github.com/adi1090x/polybar-themes
#_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/decor-glyph]
type = custom/text
format-background = ${colors.background-alt}
format-foreground = ${colors.background}

[module/decor1]
inherit = module/decor-glyph
label = "%{T3}%{T-}"

[module/decor2]
inherit = module/decor-glyph
label = "%{T3}%{T-}"

[module/decor3]
inherit = module/decor-glyph
label = "%{T3}%{T-}"

[module/decor4]
inherit = module/decor-glyph
label = "%{T3}%{T-}"