#┌────────────────────────────────────────────────────────────────┐
#│░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▄█░█▀█░█▀▄░█░█░█░░░█▀▀░█▀▀│
#│░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░█░█░█░█░█░█░█░█░░░█▀▀░▀▀█│
#│░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀░▀░▀▀▀░▀▀░░▀▀▀░▀▀▀░▀▀▀░▀▀▀│
#│░Created░By░Aditya░Shakya░@adi1090x░░░░░░░░░░░░░░░░░░░░░░░░░░░░░│
#└────────────────────────────────────────────────────────────────┘
#via Aditya░Shakya░@adi1090x @ https://github.com/adi1090x/polybar-themes
#_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/mpd]
type = internal/mpd

# Seconds to sleep between progressbar/song timer sync
interval = 1

format-online = <label-song> <bar-progress> <icon-prev> <toggle> <icon-stop> <icon-next>
format-online-prefix = "%{T6}%{T-}"
format-online-foreground = ${colors.primary}
format-online-background = ${colors.background}
format-online-padding = 1

format-playing = ${self.format-online}
format-paused = ${self.format-online}
format-stopped = ${self.format-online}

#  <label-offline>
format-offline = <label-offline>
format-offline-prefix = "%{T6}%{T-}"
format-offline-background = ${colors.background}
format-offline-padding = 1

# Available tokens:
#  %artist%
#  %album-artist%
#  %album%
#  %date%
#  %title%
label-song =  " %artist% - %title% - %album%"
label-song-maxlen = 90
label-song-ellipsis = true

# Available tokens:
#  %elapsed%
#  %total%
label-time = "| %total%"

# Available tokens:
#  None
label-offline = " Offline"

#Only applies if <icon-X> is used
icon-play = %{T6}
icon-pause = %{T6}
icon-stop = %{T6}
icon-next = %{T6}
icon-prev = %{T6}

#Used to display the state of random/repeat/repeatone/single
#Only applies if <icon-[random|repeat|repeatone|single]> is used
toggle-on-foreground = ${colors.green}
toggle-off-foreground = ${colors.red}

#Only applies if <bar-progress> is used
bar-progress-width = 45
bar-progress-indicator = >
bar-progress-fill = =
bar-progress-empty = ─

#_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_


[module/now-playing]
type = custom/script
tail = true
#format-prefix = ""
format = <label>
exec = $HOME/.config/herbstluftwm/polybar/scripts/polybar-now-playing
click-right = "kill -USR1 $(pgrep --oldest --parent %pid%)"
format-background = ${colors.background}
format-foreground = ${colors.primary}

[module/player-mpris-tail]
type = custom/script
exec = $HOME/.config/herbstluftwm/polybar/scripts/player-mpris-tail.py -f '{icon} {:artist:t18:{artist}:}{:artist: - :}{:t20:{title}:}  %{A1:~/polybar-scripts/player-mpris-tail.py previous:} ⏮ %{A} %{A1:~/polybar-scripts/player-mpris-tail.py play-pause:} {icon-reversed} %{A} %{A1:~/polybar-scripts/player-mpris-tail.py next:} ⏭ %{A}'
tail = true
format-background = ${colors.background}
format-foreground = ${colors.primary}
