#################################
####   polybar-scripts repo   ###
#################################
#https://github.com/polybar/polybar-scripts/tree/master/polybar-scripts

##########################
###  player-mpris-tail  ##
##########################
#This script displays the current track and the play-pause status without polling.
#Information is obtained by listening to MPRIS events, so it is updated instantaneously on change.
#https://github.com/polybar/polybar-scripts/tree/master/polybar-scripts/player-mpris-tail
#mpv-mpris events info: https://github.com/hoyon/mpv-mpris

#Output using mouse controls and formatters
[module/player-mpris-tail]
type = custom/script
exec = ~/polybar-scripts/player-mpris-tail.py -f '{icon} {:artist:t5:{artist}:}{:artist: - :}{:t4:{title}:}'
tail = true
click-left = ~/polybar-scripts/player-mpris-tail.py previous &
click-right = ~/polybar-scripts/player-mpris-tail.py next &
click-middle = ~/polybar-scripts/player-mpris-tail.py play-pause &

#Output using formatters and Polybar action handlers
[module/player-mpris-tail]
type = custom/script
exec = ~/polybar-scripts/player-mpris-tail.py -f '{icon} {:artist:t18:{artist}:}{:artist: - :}{:t20:{title}:}  %{A1:~/scripts/player-mpris-tail.py previous:} ⏮ %{A} %{A1:~/scripts/player-mpris-tail.py play-pause:} {icon-reversed} %{A} %{A1:~/scripts/player-mpris-tail.py next:} ⏭ %{A}'
tail = true

##########################
###  isrunning-service  ##
##########################
#A script that shows if a systemd service is running. It uses journalctl to get realtime output.
#Make sure that your user is member of the group systemd-journal to read all events.
#https://github.com/polybar/polybar-scripts/tree/master/polybar-scripts/isrunning-service
[module/isrunning-service]
type = custom/script
exec = ~/polybar-scripts/isrunning-service.sh
tail = true

###########################
###  pulseaudio-control  ##
###########################
#https://github.com/marioortizmanero/polybar-pulseaudio-control

# Usage: ./pulseaudio-control [OPTION...] ACTION

# Terminology: A node represents either a sink (output) or source (input).

# Options:
#   --autosync | --no-autosync
#         Whether to maintain same volume for all programs.
#         Default: "no"
#   --color-muted <rrggbb>
#         Color in which to format when muted.
#         Pass empty string to disable.
#         Default: "6b6b6b"
#   --notifications | --no-notifications
#         Whether to show notifications when changing nodes.
#         Default: "no"
#   --osd | --no-osd
#         Whether to display KDE's OSD message.
#         Default: "no"
#   --icon-muted <icon>
#         Icon to use when muted.
#         Default: none
#   --icon-node <icon>
#         Icon to use for node.
#         Default: none
#   --format <string>
#         Use a format string to control the output.
#         Remember to pass this argument wrapped in single quotes (`'`) instead
#         of double quotes (`"`) to avoid your shell from evaluating the
#         variables early.
#         Available variables:
#         * $VOL_ICON
#         * $VOL_LEVEL
#         * $ICON_NODE
#         * $NODE_NICKNAME
#         * $IS_MUTED (yes/no)
#         Default: '$VOL_ICON ${VOL_LEVEL}%  $ICON_NODE $NODE_NICKNAME'
#   --icons-volume <icon>[,<icon>...]
#         Icons for volume, from lower to higher.
#         Default: none
#   --node-type <node_type>
#         Whether to consider PulseAudio sinks (output) or sources (input).
#         All the operations of pulseaudio-control will apply to one of the two.
#         Pass `input` for the sources, e.g. a microphone.
#         Pass `output` for the sinks, e.g. speakers, headphones.
#         Default: "output"
#   --volume-max <int>
#         Maximum volume to which to allow increasing.
#         Default: "130"
#   --volume-step <int>
#         Step size when inc/decrementing volume.
#         Default: "2"
#   --node-blacklist <name>[,<name>...]
#         Nodes to ignore when switching. You can use globs. Don't forget to
#         quote the string when using globs, to avoid unwanted shell glob
#         extension.
#         Default: none
#   --node-nicknames-from <prop>
#         pactl property to use for node names, unless overridden by
#         --node-nickname. Its possible values are listed under the 'Properties'
#         key in the output of `pactl list sinks` and `pactl list sources`.
#         Default: none
#   --node-nickname <name>:<nick>
#         Nickname to assign to given node name, taking priority over
#         --node-nicknames-from. May be given multiple times, and 'name' is
#         exactly as listed in the output of `pactl list sinks short | cut -f2`
#         and `pactl list sources short | cut -f2`.
#         Note that you can also specify a port name for the node with
#         `<name>/<port>`.
#         It is also possible to use glob matching to match node and port names.
#         Exact matches are prioritized. Don't forget to quote the string when
#         using globs, to avoid unwanted shell glob extension.
#         Default: none
#   --listen-timeout-secs
#         The listen command updates the output as soon as it receives an event
#         from PulseAudio. However, events are often accompanied by many other
#         useless ones, which may result in unnecessary consecutive output
#         updates. This script buffers the following events until a timeout is
#         reached to avoid this scenario, which lessens the CPU load on events.
#         However, this may result in noticeable latency when performing many
#         actions quickly (e.g., updating the volume with the mouse wheel). You
#         can specify what timeout to use to control the responsiveness, in
#         seconds.
#         Default: "0.05"

# Actions:
#   help              display this message and exit
#   output            print the PulseAudio status once
#   listen            listen for changes in PulseAudio to automatically update
#                     this script's output
#   up, down          increase or decrease the default node's volume
#   mute, unmute      mute or unmute the default node's audio
#   togmute           switch between muted and unmuted
#   next-node         switch to the next available node
#   sync              synchronize all the output streams volume to be the same as
#                     the current node's volume

# Author:
#     Mario Ortiz Manero