#┌──────────────────────────────────────────────────────────────────────────────-----┐
#│░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█░█░█▀▀░█▀▀░█▀▄░░░█▄█░█▀█░█▀▄░█░█░█░░░█▀▀░█▀▀ │
#│░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░█░▀▀█░█▀▀░█▀▄░░░█░█░█░█░█░█░█░█░█░░░█▀▀░▀▀█ │
#│░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀▀░▀▀▀░▀▀▀░▀░▀░░░▀░▀░▀▀▀░▀▀░░▀▀▀░▀▀▀░▀▀▀░▀▀▀ │
#│░Created░By░Aditya░Shakya░@adi1090x░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░│
#└──────────────────────────────────────────────────────────────────────────────-----┘
#via Aditya░Shakya░@adi1090x @ https://github.com/adi1090x/polybar-themes
#_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/polywinner]
type = custom/script
exec = $XDG_CONFIG_HOME/herbstluftwm/polybar/scripts/polywinner
tail = true
format-background = ${colors.background}

[module/updates-pacman-aurhelper]
type = custom/script
exec = $XDG_CONFIG_HOME/herbstluftwm/polybar/scripts/updates-pacman-aurhelper.sh
interval = 60
# label = "%{T6}  %{T-}"
label-background = ${colors.background}
label-foreground = ${colors.primary}

[module/xwindow]
type = internal/xwindow
padding = 2 2
label = "%title:0:60:...%"
label-background = ${colors.background}
label-empty = "Arch Linux"
label-empty-background = ${colors.background}

[module/xworkspaces]
type = internal/xworkspaces

padding = 2

label-active = "%name%"
label-active-background = ${colors.base3}
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = "%name%"
label-occupied-padding = 1
label-occupied-background = ${colors.background}

label-urgent = "%name%"
label-urgent-foreground = ${colors.base3}
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = "%name%"
label-empty-foreground = ${colors.disabled}
label-empty-background = ${colors.background}
label-empty-padding = 1

[module/systray]
type = internal/tray
format-foreground = ${colors.background}
format-background = ${colors.background}
format-padding = 0
tray-size = 16pt
tray-padding = 4pt
tray-background = ${colors.background}
