--# conky --config=$HOME/.config/herbstluftwm/conky/solarized-l-neofetch-rice.conf
--##################################################
--## VinDSL | rev 16-09-02 13:53 | ver 1.10.1-P7  ##
--##################################################
--##             August 2016 Series               ##
--##################################################
--# WARNING: Heavily modified by LiterallySomeCat aka Lannakin
--#
--# rebuild font cache file: fc-cache -fv
conky.config = {

use_xft = true,
xftalpha = 1,
override_utf8_locale = true,
text_buffer_size = 1592,
max_user_text = 32768,
uppercase = false,
top_name_width = 10,
short_units = true,
pad_percents = 0,

background = true,
update_interval = 1.0,
total_run_times = 0,
own_window = true,
own_window_class = 'Conky',
own_window_colour = '#FDF6E3',
own_window_transparent = false,
own_window_type = 'desktop',
own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
own_window_argb_visual = true,
own_window_argb_value = 245,

imlib_cache_size = 1,
double_buffer = true,
draw_shades = false,
default_color = '#586E75',
default_shade_color = '#586E75',
draw_outline = false,
draw_borders = true,
draw_graph_borders = false,
draw_shades = false;  --# ugly text shadow
out_to_ncurses = false,
out_to_console = false,

alignment = 'top_left',
minimum_width = 267,
minimum_height = 153,
gap_x = 3451,
gap_y = 33,
border_inner_margin = 7,
border_outer_margin = 0,
border_width = 2,
use_spacer = 'right',
no_buffers = true,

--# cpu_avg_samples = 200,
--# net_avg_samples = 200,

font0 = 'Px437 CompaqThin 8x8:size=6',
font1 = 'Px437 Compaq Port3:normal:size=12',

color0 = '#073642',
color1 = '#657B83',
color2 = '#93A1A1',
color3 = '#cfcabc',
color4 = '#FDF6E3',
color6 = '#CB4B16',
color7 = '#859900',
color8 = '#B8D8D6',
color9 = '#C5E7E5',
}
conky.text = [[
# #002B36 #586E75 #839496 #EEE8D5 #B58900 #DC322F #6C71C4 #2AA198 #B8D8D6
# #073642 #657B83 #93A1A1 #FDF6E3 #CB4B16 #D33682 #268bC2 #859900 #C5E7E5
##################################
##     HERBSTLUFTWM CONTROL     ##
##################################
${voffset 0}${font1}${#2AA198}HERBSLUFTWM - NEOFETCH${offset 4}${color8}${voffset -2}${hr 2}
${voffset 5}${font0}${color2}${execp neofetch}${font}
${voffset 2}
]]