-- /config/lazyvim-icons.lua
-- disabled if below line is active
-- if true then return {} end

return {
  kind = {
    EnumMember = ' ',
    Field = ' ',
    File = ' ',
    Folder = '󰉋 ',
    Function = ' ',
    Keyword = ' ',
    Module = ' ',
    Namespace = ' ',
    Null = '󰟢 ',
    Operator = ' ',
    Package = ' ',
    Property = ' ',
    Reference = ' ',
    Snippet = ' ',
    String = ' ',
    Struct = ' ',
  },
  git = {
    LineAdded = ' ',
    LineModified = ' ',
    LineRemoved = ' ',
    FileDeleted = ' ',
    FileIgnored = '◌',
    FileRenamed = ' ',
    FileStaged = 'S',
    FileUnmerged = '',
    FileUnstaged = '',
    FileUntracked = 'U',
    Diff = ' ',
    Octoface = ' ',
    Branch = '',
  },
  ui = {
    ArrowCircleDown = '',
    ArrowCircleLeft = '',
    ArrowCircleRight = '',
    ArrowCircleUp = '',
    BoldArrowDown = '',
    BoldArrowLeft = '',
    BoldArrowRight = '',
    BoldArrowUp = '',
    BoldClose = '',
    BoldDividerLeft = '',
    BoldDividerRight = '',
    BoldLineLeft = '▎',
    BoxChecked = ' ',
    Stacks = '',
    DebugConsole = ' ',
    Check = '',
    ChevronRight = '',
    ChevronShortDown = '',
    ChevronShortLeft = '',
    ChevronShortRight = '',
    ChevronShortUp = '',
    Circle = ' ',
    Close = '󰅖',
    CloudDownload = ' ',
    Code = '',
    Dashboard = '',
    DividerLeft = '',
    DividerRight = '',
    DoubleChevronRight = '»',
    EmptyFolder = ' ',
    EmptyFolderOpen = ' ',
    FileSymlink = '',
    Files = ' ',
    FindFile = '󰈞',
    FindText = '󰊄',
    Fire = '',
    Folder = '󰉋 ',
    FolderOpen = ' ',
    FolderSymlink = ' ',
    Forward = ' ',
    Gear = ' ',
    List = ' ',
    Note = ' ',
    Package = ' ',
    Pencil = '󰏫 ',
    Plus = ' ',
    Tab = '󰌒 ',
    Table = ' ',
    Target = '󰀘 ',
    Telescope = ' ',
    Text = ' ',
    Tree = '',
    Triangle = '󰐊',
    TriangleShortArrowDown = '',
    TriangleShortArrowLeft = '',
    TriangleShortArrowRight = '',
    TriangleShortArrowUp = '',
  },
  diagnostics = {
    BoldError = '',
    BoldWarning = '',
    BoldInformation = '',
    BoldQuestion = '',
    Question = '',
    BoldHint = '',
    Trace = '✎',
  },
}
