#┌────────────────────────────────────────────────────────────┐
#│░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▀▀░█▀█░█▀█░█▀▀░▀█▀░█▀▀│
#│░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░░░█░█░█░█░█▀▀░░█░░█░█│
#│░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀▀░▀▀▀░▀░▀░▀░░░▀▀▀░▀▀▀│
#│░Created░By░Aditya░Shakya░@adi1090x░░░░░░░░░░░░░░░░░░░░░░░░░│
#└────────────────────────────────────────────────────────────┘
# via Aditya░Shakya░@adi1090x @ https://github.com/adi1090x/polybar-themes
#_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[global/wm]
wm-name = herbstluftwm
# wm-restack    = generic
# wm-restack    = bspwm
# wm-restack    = i3
wm-restack = ewmh

enable-struts = false
# margin-bottom = 1.
# margin-top = 1.6

#_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

#File Inclusion
include-file = $HOME/.config/herbstluftwm/polybar/components/bars.ini
include-file = $HOME/.config/herbstluftwm/polybar/components/colors.ini
include-file = $HOME/.config/herbstluftwm/polybar/components/decor_modules.ini
include-file = $HOME/.config/herbstluftwm/polybar/components/modules.ini
include-file = $HOME/.config/herbstluftwm/polybar/components/mpd_modules.ini
include-file = $HOME/.config/herbstluftwm/polybar/components/user_modules.ini
include-file = $HOME/.config/herbstluftwm/polybar/components/web_modules.ini

#_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

# Bar Settings
[bar/main]
# If unspecified, application will pick the first one it finds.
monitor-fallback =
monitor-strict = false
override-redirect = false

bottom = false
fixed-center = true
width = 100%
height = 20
# Number of spaces to add at the beginning/end of the bar
# padding-{left,right}
padding = 0
offset-x = 0%
offset-y = 0%
background = ${colors.background-alt}
foreground = ${colors.foreground}

radius-top = 0.0
radius-bottom = 0.0
#overline,underline
line-size = 3
line-color = ${colors.primary}
#  border-{left,top,right,bottom}
#  width - border-right-size - border-left-size
border-size = 0
border-color = ${colors.primary}
# Number of spaces to add before/after each module
#  module-margin-{left,right}
module-margin = 0

# Set DPI value used when rendering text
# dpi =

#_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

# rebuild font cache file: fc-cache -fv
# Text Fonts
font-0 = "Px437CompaqPort3 Nerd Font Mono Plus Font Awesome:size=10;2"
# Icon Fonts
font-1 = "PowerlineSymbols:size=12;3"
# Powerline Glyphs
font-2 = "PowerineSymbols:size=19;3"
# bar decor glyphs
font-3 = "Iosevka Nerd Font:style=Medium::size=16;4"
# Smaller font size for shorter spaces
font-4 = "Px437CompaqPort3 Nerd Font Mono Plus Font Awesome:size=20;4"

# retro style symbols font
font-5 = "Siji0:size=13:weight=book;2"

font-6 = "Iosevka Nerd Font:style=Medium:size=7;4"

#_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[bar/top]
inherit = bar/main
modules-left = mpd decor1
modules-right = decor4 decor3 decor4 network-networkmanager updates-pacman-aurhelper
enable-ipc = true

monitor = DisplayPort-2

[bar/bottom]
inherit = bar/main
bottom = true
modules-left = xworkspaces polywinner decor3
modules-right = decor2 xkeyboard network cpu pulseaudio systray dunst date
enable-ipc = true

monitor = DisplayPort-2

[bar/aux0]
inherit = bar/main
bottom = true
modules-left = xworkspaces polywinner decor3
# modules-right = decor2 xkeyboard network cpu pulseaudio systray dunst date
enable-ipc = true

monitor = DisplayPort-0

[bar/aux1]
inherit = bar/main
bottom = true
modules-left = xworkspaces polywinner decor3
# modules-right = decor2 xkeyboard network cpu pulseaudio systray dunst date
enable-ipc = true

monitor = DisplayPort-1

#_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

# between the output of each module
separator =

# Locale used to localize various module data (e.g. date)
# Expects a valid libc locale, for example: sv_SE.UTF-8
locale =

# Fallback click handlers
click-left =
click-middle =
click-right =
scroll-up =
scroll-down =
double-click-left =
double-click-middle =
double-click-right =

[settings]
# Reload upon receiving XCB_RANDR_SCREEN_CHANGE_NOTIFY events
screenchange-reload = false

# Compositing operators
# @see: https://www.cairographics.org/manual/cairo-cairo-t.html#cairo-operator-t
compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over