-- /plugins/which-key.lua
-- disabled if below line is active
-- if true then return {} end
return {
  {
    "folke/which-key.nvim",
    event = "VeryLazy",
    opts = {
      -- colors = { Normal = "Search" },
      ---@type false | "classic" | "modern" | "helix"
      preset = "helix",
      ---@type wk.Win.opts
      win = {
        border = "single",
        relative = "win",
        focusable = "false",
        noautocmd = "true",
        style = "minimal",
        -- wo = {
        --   -- missing fields :) --
        --   arab = "",
        --   arabic = "",
        --   breakindent = "",
        --   breakindentopt = "",
        --   bri = "",
        --   briopt = "",
        --   cc = "",
        --   cocu = "",
        --   cole = "",
        --   colorcolumn = "",
        --   concealcursor = "",
        --   conceallevel = "",
        --   crb = "",
        --   cuc = "",
        --   cul = "",
        --   culopt = "",
        --   cursorbind = "",
        --   cursorcolumn = "",
        --   diff = "",
        --   eiw = "",
        --   eventignorewin = "",
        --   fcs = "",
        --   fdc = "",
        --   fde = "",
        --   fdi = "",
        --   fdl = "",
        --   fdm = "",
        --   fdn = "",
        --   fdt = "",
        --   fen = "",
        --   fillchars = "",
        --   fml = "",
        --   fmr = "",
        --   foldexpr = "",
        --   foldignore = "",
        --   foldlevel = "",
        --   foldmarker = "",
        --   foldmethod = "",
        --   foldminlines = "",
        --   foldnestmax = "",
        --   foldtext = "",
        --   lbr = "",
        --   lcs = "",
        --   linebreak = "",
        --   listchars = "",
        --   nu = "",
        --   number = "",
        --   numberwidth = "",
        --   nuw = "",
        --   previewwindow = "",
        --   pvw = "",
        --   relativenumber = "",
        --   rightleft = "",
        --   rightleftcmd = "",
        --   rl = "",
        --   rlc = "",
        --   rnu = "",
        --   sbr = "",
        --   scb = "",
        --   scl = "",
        --   scr = "",
        --   scroll = "",
        --   scrollbind = "",
        --   showbreak = "",
        --   sidescrolloff = "",
        --   signcolumn = "",
        --   siso = "",
        --   smoothscroll = "",
        --   sms = "",
        --   so = "",
        --   statuscolumn = "",
        --   stc = "",
        --   stl = "",
        --   ve = "",
        --   virtualedit = "",
        --   wbr = "",
        --   wfb = "",
        --   wfh = "",
        --   wfw = "",
        --   winbl = "",
        --   winblend = "",
        --   winfixbuf = "",
        --   winfixheight = "",
        --   winfixwidth = "",
        --   winhl = "",
        --   -- missing fields :) --
        --   scrolloff = 0,
        --   foldenable = false,
        --   winhighlight = "Normal:WhichKeyNormal,FloatBorder:WhichKeyBorder,FloatTitle:WhichKeyTitle",
        --   winbar = "",
        --   statusline = "",
        --   wrap = false,
        -- },
      },
    },
  },
}
