#!/usr/bin/env bash
# autostart
#
### HERBSTLUFTWM AUTOSTART ####################################################
#
# SCRIPT NAME: autostart
# AUTHOR: Literally Some Cat        <https://github.com/Lannakin>
# VERSION DATE: 2026-09-10
# VERSION: 2.2.1                    <https://semver.org/>
# ORIGINAL AUTHOR: Thorsten Wißmann <https://github.com/herbstluftwm>
# LICENSE: Simplified BSD License
#          <https://github.com/herbstluftwm/herbstluftwm?tab=License0-ov-file>
#
# DESCRIPTION:
# Herbstluftwm runs this script when launching initially as well as upon being
# commanded to reload.
#
# REVISION HISTORY:
# full edits at:
# <https://github.com/herbstluftwm/herbstluftwm/commits/master/share/autostart>
#
# VERSION:  MM. [MAJOR].[MINOR].[PATCH]
#
# YYYY-MM-DD  VERSION   AUTHOR              DESCRIPTION OF CHANGES
# 2025-09-14  0.0.0     Literally Some Cat  Initial creation
# 2025-09-15  0.1.0     Literally Some Cat  Edited logging, linted,
# 2025-12-01  1.1.0     Literally Some Cat  Added header, major logging format
#                                           edits
# 2026-08-21  1.2.0     Literally Some Cat  Corrected paths to use XDG envvars.
# 2026-08-21  1.2.1     Literally Some Cat  Corrected debug output.
# 2026-09-01  2.0.0     Literally Some Cat  Moved app autostart to functions.
# 2026-09-02  2.1.0     Literally Some Cat  Moved picom to systemd kinda.
# 2026-09-09  2.2.0     Literally Some Cat  Added tags for certain apps.
# 2026-09-10  2.2.1     Literally Some Cat  Reverted many changes from 2.0.0
#                                           due to inconsistent detection of
#                                           lockfile.  Reverted weird file-wide
#                                           increment of many numbers by 1.
#
###############################################################################
#                                                                             #
# LOGFILE MESSAGE SYNTAX:                                                     #
# YYYY-MM-DD HH:MM:SS script-name|loglevel: the message                       #
#                                                                             #
# LOG LEVELS:                                                                 #
# error: a fatal fucking error                                                #
# warning: an error that is not immediately fatal                             #
# info: a normal operational message                                          #
# debug: a message that should only be used for testing and diagnostics       #
#                                                                             #
###############################################################################
# config for herbstluftwm

#        +----------------------------------------------------------+
#        |                     GLOBALS SECTION                      |
#        +----------------------------------------------------------+

# --| GLOBAL VARIABLES |-------------------------------------------------------
# HLWM_DIR="$(dirname -- "$1")"
# shellcheck disable=SC2154
HLWM_DIR="${XDG_CONFIG_HOME}/herbstluftwm"
HLWM_SCRIPTS_DIR="${XDG_CONFIG_HOME}/herbstluftwm/scripts"
# specify which desktop environment is in use
# shellcheck disable=SC2035
XDG_SESSION_DESKTOP="herbstluftwm"

# --| SOURCE |-----------------------------------------------------------------
# source container for more global variables
source "${HOME}/scripts/get-script-dir"
source "${HOME}/.bashrc"
source "${HOME}/.xprofile"
source "${HLWM_DIR}"/herbstluftwm-env
source "${XDG_CONFIG_HOME}"/lsc-environment/bash-run-commands

# --| LOGGING VARIABLES |------------------------------------------------------
# warning: lazy AF
SCRIPTNAME="herbstluftwm"
# timestamp format
TIMESTAMP="$(date +"%Y-%m-%d %H:%M:%S")"
# LOGLEVEL: decrease index with increasing severity
L3="${TIMESTAMP} ${SCRIPTNAME}|debug:"
L2="${TIMESTAMP} ${SCRIPTNAME}|info:"
# L1="${TIMESTAMP} ${SCRIPTNAME}|warning:"
# L0="${TIMESTAMP} ${SCRIPTNAME}|error:"

# send the entirety of autostart's execution to the log
exec 1>"${HERBSTLUFTWMLOG}" 2>&1
echo "---  herbstluftwm: running autostart script ---"
echo "${L2} LOGFILE is ${HERBSTLUFTWMLOG}"

# print sourced variables
echo "${L3} HERBSTLUFTWMLOG is ${HERBSTLUFTWMLOG}"
echo "${L3} NOTIFICATIONDAEMONLOG is ${NOTIFICATIONDAEMONLOG}"
echo "${L3} STATUSBARLOG is ${STATUSBARLOG}"
echo "${L3} XRANDRLOG is ${XRANDRLOG}"
echo "${L3} KEYBINDMANAGERLOG is ${KEYBINDMANAGERLOG}"
echo "${L3} STATUSBARHEIGHT is ${STATUSBARHEIGHT}"
# echo "${L3} HLWM_AUTOSTART_DIR is ${HLWM_AUTOSTART_DIR}"

#        +----------------------------------------------------------+
#        |                     STARTUP SECTION                      |
#        +----------------------------------------------------------+

hc() {
  herbstclient "$@"
}

hc emit_hook reload
export XDG_SESSION_DESKTOP=herbstluftwm
# hc setenv XDG_SESSION_DESKTOP=herbstluftwm

#        +----------------------------------------------------------+
#        |                     KEYBINDS SECTION                     |
#        +----------------------------------------------------------+

hc keyunbind --all # remove all existing keybindings

# --| MODIFIER SWAP |----------------------------------------------------------
# via running command: xmodmap
# xmodmap:  up to 4 keys per modifier, (keycodes in parentheses):
#
# mod1        Alt_L            (0x40),  Alt_R     (0x6c),  Alt_L   (0xcc),  Meta_L (0xcd)
# mod2        Num_Lock         (0x4d)
# mod3        ISO_Level5_Shift (0xcb)
# mod4        Super_L          (0x85),  Super_R   (0x86),  Super_L (0xce)
# mod5        ISO_Level3_Shift (0x5c)
# control     Control_L        (0x25),  Control_R (0x69)
# lock        Caps_Lock        (0x42)
# shift       Shift_L          (0x32),  Shift_R   (0x3e)
#
# xmodmap / herbstluftwm may report that Mod1 is an Unknown KeySym, but mod1 is
# not functional lol

Mod=Mod1 # Use alt as the main modifier

# --| MOUSE BINDS |------------------------------------------------------------
hc mouseunbind --all # remove all existing keybindings

hc mousebind "${Mod}"-Shift-Button1 move  # use mouse to move a client or frame
hc mousebind "${Mod}"-Button3 resize      # resize frame as well

# --| WINDOW MANAGEMENT |-------------------------------------------------------
hc keybind "${Mod}"-Shift-q quit   # quit hlswm
hc keybind "${Mod}"-Shift-r reload # reload hlswm
hc keybind "${Mod}"-Shift-c close  # close focused window or frame

# --| CYCLE FOCUS |------------------------------------------------------------
hc keybind "${Mod}"-BackSpace cycle_monitor # cycle focus to next monitor
hc keybind "${Mod}"-Tab cycle_all +1        # cycle focus to next frame on same monitor; forward 1
hc keybind "${Mod}"-Shift-Tab cycle_all -1  # cycle focus to next frame on same monitor; backward 1
hc keybind "${Mod}"-c cycle                 # cycle focus to next client in the same frame

# --| MOVEMENT -- FOCUSED CLIENT |---------------------------------------------
# tiling and floating mode
hc keybind "${Mod}"-Left focus left
hc keybind "${Mod}"-Down focus down
hc keybind "${Mod}"-Up focus up
hc keybind "${Mod}"-Right focus right

# --| MOVEMENT -- CLIENTS |----------------------------------------------------
# moving clients between frames in tiling and floating mode
hc keybind "${Mod}"-Shift-Left shift left
hc keybind "${Mod}"-Shift-Down shift down
hc keybind "${Mod}"-Shift-Up shift up
hc keybind "${Mod}"-Shift-Right shift right

# --| FRAME SPLITTING |--------------------------------------------------------
# create an empty frame at location of focused monitor
hc keybind "${Mod}"-i split bottom 0.5 # split fovused frame vertically
hc keybind "${Mod}"-o split right 0.5  # split focused frame horizontally

hc keybind "${Mod}"-Control-space split explode # explode current frame into subframes

# --| RESIZING |---------------------------------------------------------------
# resizes frames and floating clients
resizestep=0.01
hc keybind "${Mod}"-Control-Up resize up +"${resizestep}"
hc keybind "${Mod}"-Control-Left resize left +"${resizestep}"
hc keybind "${Mod}"-Control-Down resize down +"${resizestep}"
hc keybind "${Mod}"-Control-Right resize right +"${resizestep}"

# --| LAYOUT |-----------------------------------------------------------------
# hc keybind "${Mod}"-f floating toggle   # per focused FRAME
hc keybind "${Mod}"-l fullscreen toggle # per focused
hc keybind "${Mod}"-t pseudotile toggle # per focused
hc keybind "${Mod}"-r remove            # removes frame, merges contents with neighboring; per focused# per focused CLIENT

hc keybind "${Mod}"-f set_attr clients.focus.floating toggle        # toggle floating on focused CLIENT
hc keybind "${Mod}"-Shift-d set_attr clients.focus.decorated toggle # toggle decorations on focused CLIENT

# toggle between grid and max tab layout
hc keybind "${Mod}"-Ctrl-m spawn "${HLWM_SCRIPTS_DIR}"/maximize.sh

# --| MINIMIZING |-------------------------------------------------------------
hc keybind "${Mod}"-Shift-m set_attr clients.focus.minimized true # minimizes focused window
hc keybind "${Mod}"-t pseudotile toggle                           # per focused
hc keybind "${Mod}"-r remove                                      # removes frame, merges contents with neighboring; per focused# per focused CLIENT

hc keybind "${Mod}"-Shift-f set_attr clients.focus.floating toggle  # toggle floating on focused CLIENT
hc keybind "${Mod}"-Shift-d set_attr clients.focus.decorated toggle # toggle decorations on focused CLIENT

# toggle between grid and max tab layout
hc keybind "${Mod}"-Ctrl-Shift-m spawn "${HLWM_SCRIPTS_DIR}"/maximize.sh

# --| MINIMIZING |-------------------------------------------------------------
hc keybind "${Mod}"-Shift-m set_attr clients.focus.minimized true # minimizes focused window
hc keybind "${Mod}"-Control-m jumpto last-minimized               # jump to minimized windows sequentially and unminimize them

# unminimize all minimized clients on the current tag
hc keybind "${Mod}"-Ctrl-Shift-m substitute FOCUS "tags.focus.name" \
  foreach CLIENT clients. \
  sprintf MINATT "%c.minimized" CLIENT \
  sprintf TAGATT "%c.tag" CLIENT and \
  , compare MINATT "=" "true" \
  , compare TAGATT "=" FOCUS \
  , set_attr MINATT false
echo "${L3} set layout keybinds"

# --| LAYOUT SAVE & RECALL |---------------------------------------------------
# hc keybind "${Mod}"-Control-k        spawn "${HLWM_SCRIPTS_DIR}"/save-layout.sh
# hc keybind "${Mod}"-Control-comma    spawn "${HLWM_SCRIPTS_DIR}"/recall-layout.sh

# --| LAYOUT SAVE & RECALL VIA DMENU |-----------------------------------------
hc keybind "${Mod}"-Control-k spawn "${HLWM_SCRIPTS_DIR}"/herbstluftwm-save-tree.sh save
hc keybind "${Mod}"-Control-comma spawn "${HLWM_SCRIPTS_DIR}"/herbstluftwm-save-tree.sh load
echo "${L3} set layout save & recall via dmenu keybinds"

# --| SCREENSHOT SELECTION |---------------------------------------------------
# hc keybind "${Mod}"-Shift-s spawn "${HLWM_SCRIPTS_DIR}"/screenshot.sh
# echo "${L3} set screenshot selection keybind"

#        +----------------------------------------------------------+
#        |                       TAGS SECTION                       |
#        +----------------------------------------------------------+

# --| monitor-agnostic tag lists |---------------------------------------------

tag_names=({0..3})
tag_keys=({1..4} 0)

hc silent rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}"; do
  hc add "${tag_names[$i]}"
  key="${tag_keys[$i]}"
  if [ -n "$key" ]; then
    hc keybind "$Mod-$key" use_index "$i"
    hc keybind "$Mod-Shift-$key" move_index "$i"
  fi
done
echo "${L3} set tag lists"

### CYCLING TAGS ###
hc keybind "${Mod}"-period use_index +1 --skip-visible
hc keybind "${Mod}"-comma use_index -1 --skip-visible
echo "${L3} set cycle tags keybinds"

# # --| per-programm tags |------------------------------------------------------
# # these are intended to be used to set per-tag rules in the RULES SECTION
#
# # tag for vimpc
# hc add tag_vimpc
#
# # kicad
# hc add tag_kicad
#
# # vesktop
# hc add tag_vesktop
#
# # galculator
# hc add tag_galculator
#
#        +----------------------------------------------------------+
#        |                      THEME SECTION                       |
#        +----------------------------------------------------------+

# #002B36 #586E75 #839496 #EEE8D5 #B58900 #DC322F #6C71C4 #2AA198
# #073642 #657B83 #93A1A1 #FDF6E3 #CB4B16 #D33682 #268bC2 #859900

hc set verbose false
hc set wmname herbstluftwm

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

# --| FRAME STYLE |------------------------------------------------------------
hc set frame_border_active_color '#CB4B16dd'
hc set frame_border_normal_color '#657B83cc'
hc set frame_bg_normal_color '#C5E7E5FF'
hc set frame_bg_active_color '#B8D8D6FF'
hc set frame_bg_transparent on
hc set frame_transparent_width 1
hc set frame_gap 4
hc set frame_padding 0
hc set frame_border_width 1
hc set show_frame_decorations 'nonempty'
#hc set tight_decorations         true

# --| WINDOW STYLE |-----------------------------------------------------------
hc set window_gap 1
hc set gapless_grid true
hc set smart_window_surroundings on
hc set smart_frame_surroundings on
hc set tabbed_max true
hc set mouse_recenter_gap 0

# --| TITLE BAR STYLE |--------------------------------------------------------
hc attr theme.title_height 14
hc attr theme.title_when 'one_tab'
hc attr theme.title_font 'Px437 Compaq Port3:pixelsize=12' # for XFT fonts
# hc attr theme.title_font '-*-fixed-medium-r-*-*-13-*-*-*-*-*-*-*' # for standard bitmap fonts
hc attr theme.title_depth 2 # space below the title's baseline
hc attr theme.active.color '#93A1A1'
hc attr theme.title_color '#002B36'
hc attr theme.normal.color '#FDF6E3dd'
hc attr theme.urgent.color '#CB4B16dd'
hc attr theme.tab_color '#EEE8D5dd'
hc attr theme.active.tab_color '#B8D8D6dd'
hc attr theme.active.tab_outer_color '#C5E7E5dd'
hc attr theme.active.tab_title_color '#002B36'
hc attr theme.normal.title_color '#657B83'
hc attr theme.inner_width 0
hc attr theme.inner_color '#93A1A1'
hc attr theme.border_width 1
hc attr theme.active.border_width 1
hc attr theme.floating.border_width 1
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color '#839496'
hc attr theme.active.inner_color '#CB4B16'
hc attr theme.urgent.inner_color '#D33682'
hc attr theme.normal.inner_color '#C5E7E5'
hc attr theme.background_color '#93A1A1bb'
hc attr theme.tiling.outer_width 1

# copy inner color to outer_color
for state in active urgent normal; do
  hc substitute C theme."${state}".inner_color attr theme."${state}".outer_color C
done

#        +----------------------------------------------------------+
#        |                      RULES SECTION                       |
#        +----------------------------------------------------------+

hc unrule -F

hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
hc rule fixedsize floating=on

# hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on floating=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# TODO: set per-tag rules

# rule [[--]FLAG|[--]LABEL|[--]CONDITION|[--]CONSEQUENCE …]
#
# hc rule title~'[Gg]alculator' tag=tag_galculator
# vimpc is like kitty - vimpc or something
#

hc rule title='Font Forge' floating=on
hc rule title='Font Information.*' floating=on
hc rule title='Spectacle' floating=on
hc rule class='zenity' floating=on
hc rule class~'[Cc]onky' manage=off
hc rule class~'[Gg]alculator' floating=on
hc rule class='[Ss]pectacle' manage=off
hc rule class='[Ss]crot' manage=off

hc rule class=Keybindings floating=on
hc rule class=Music floating=on
hc rule class=Sysinfo floating=on
hc rule class~'[Gg]pick' floating=on

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

#        +----------------------------------------------------------+
#        |                     MONITORS SECTION                     |
#        +----------------------------------------------------------+

# --| DEFINE MONITOR SIZES AND POSITIONS |-------------------------------------
# xrandr -q | grep " connected" | cut -d ' ' -f1
# hc list_monitors --no-disjoin

echo "${L2} initializing monitors..."

hc set_monitors 2560x1440+0+0 3440x1440+2560+0 2560x1440+6000+0

# hc pad <id> "top" "right" "bottom" "left"
hc pad 0 "0" "0" "0" "0"
hc pad 1 "0" "0" "${STATUSBARHEIGHT}" "0"
hc pad 2 "${STATUSBARHEIGHT}" "0" "${STATUSBARHEIGHT}" "0"

# output settings to log, in case display layout seems wrong
hc list_monitors --no-disjoin | while IFS= read -r line; do
  echo "${L2} $line"
done

# --| DEFINE BEHAVIOR |--------------------------------------------------------
hc set focus_crosses_monitor_boundaries 1
hc set swap_monitors_to_get_tag 0

#        +----------------------------------------------------------+
#        |              EXTERNAL APP AUTOSTART SECTION              |
#        +----------------------------------------------------------+

systemctl --user start herbstluftwm-session.target

# --| CLEAN HOME |-------------------------------------------------------------
# echo "${L3} PATH is $PATH"
"clean-up-home-dir" &
echo "${L2} running clean-up-home-dir; fuck you, miscreants"

# variable for flag file to mark herbstluftwm as initiated this session
INIT_FLAG_FILE="/tmp/window-manager-init.lck"
HLWM_INITIALIZED=0

# echo "${L3} HLWM_INITIALIZED=$HLWM_INITIALIZED"

if [[ -e "${INIT_FLAG_FILE}" ]]; then
  HLWM_INITIALIZED=1
  echo "${L2} initialization flag file located at ${INIT_FLAG_FILE}."
else
  HLWM_INITIALIZED=0
  echo "${L2} no initialization flag file located at ${INIT_FLAG_FILE}."
fi

# --| DISPLAY CONFIGURATION |--------------------------------------------------
echo "${L2} setting up monitor layouts"
xrandr --dpi 109.68/DisplayPort-0 --dpi 122.38/DisplayPort-1 --dpi 96/DisplayPort-2 >"${XRANDRLOG}" &
xrandr --output DisplayPort-0 --mode 2560x1440 --rate 75 &
xrandr --output DisplayPort-1 --mode 3440x1440 --rate 144 --primary &
xrandr --output DisplayPort-2 --mode 2560x1440 --rate 75 &

# window layouts
if [[ $HLWM_INITIALIZED = 0 ]]; then
  "${HLWM_SCRIPTS_DIR}"/herbstluftwm-after.sh
fi
# --| DESKTOP ENVIRONMENT |----------------------------------------------------
"${HLWM_SCRIPTS_DIR}"/herbstluftwm-start.sh --polybar &>"${STATUSBARLOG}" &
echo "${L2} starting polybar using herbstluftwm-start.sh --polybar"

# compositor
# picom &
systemctl --user start picom
echo "${L2} starting picom compositor"

# status display
"${HLWM_SCRIPTS_DIR}"/herbstluftwm-start.sh --conky &
echo "${L2} starting conky using herbstluftwm-start.sh --conky"

# notification daemon
dunstctl reload "${XDG_CONFIG_HOME}"/herbstluftwm/dunstrc &>"${NOTIFICATIONDAEMONLOG}" &
echo "${L2} starting dunst using ${XDG_CONFIG_HOME}/herbstluftwm/dunstrc"

# xscreensaver
xscreensaver --no-splash --log /dev/null &
# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent0 &
echo "${L2} starting xscreensaver"

# --| INTERFACE DESIGN CONTROL |-----------------------------------------------
"${HLWM_SCRIPTS_DIR}"/herbstluftwm-start.sh --sxhkd &
echo "${L2} starting sxhkd using herbstluftwm-start.sh --sxhkd"

input-remapper-control --config-dir "${XDG_CONFIG_HOME}"/input-remapper-1/ --command autoload &>/dev/null
echo "${L2} setting input-remapper-control --config-dir ${XDG_CONFIG_HOME}/input-remapper-2/ --command autoload"

# sleep 2

# create flag file to make herbstluftwm as having initiated
if [[ $HLWM_INITIALIZED = 0 ]]; then
  echo "${L2} initialization flag file detected at $INIT_FLAG_FILE"
else
  touch "${INIT_FLAG_FILE}"
  echo "${L2} initialization flag file created at $INIT_FLAG_FILE"
fi

echo "---  herbstluftwm: end of autostart file ---"
