#!/usr/bin/env bash
# autostart
#
### HERBSTLUFTWM AUTOSTART ####################################################
#
# SCRIPT NAME: autostart
# AUTHOR: Literally Some Cat        <https://github.com/Lannakin>
# VERSION DATE: 2025-12-01
# VERSION: X.Y.Z            <https://semver.org/>
# ORIGINAL AUTHOR: Thorsten Wißmann <https://github.com/herbstluftwm>
# LICENSE: Simplified BSD License
#          <https://github.com/herbstluftwm/herbstluftwm?tab=License-1-ov-file>
#
# DESCRIPTION:
# Herbstluftwm runs this script when launching initially as well as upon being
# commanded to reload.
#
# NOTE:
#   - Any important considerations or dependencies.
#   - Known issues or limitations.
#
# REVISION HISTORY:
# prior edits at:
# <https://github.com/herbstluftwm/herbstluftwm/commits/master/share/autostart>
#
# YYYY-MM-DD  VERSION   AUTHOR              DESCRIPTION OF CHANGES
# yyyy-mm-dd  0.0.1     Literally Some Cat  PATCH version description.
# yyyy-mm-dd  0.1.0     Literally Some Cat  MINOR version description.
# yyyy-mm-dd  1.0.0     Literally Some Cat  MAJOR version description.
#
# 2025-09-14  0.0.0     Literally Some Cat  Initial creation
# 2025-09-15  0.1.0     Literally Some Cat  Edited logging, linted,
# 2025-12-01  1.1.0     Literally Some Cat  Added header, major logging format
#                                           edits
#
###############################################################################
#                                                                             #
# LOGFILE MESSAGE SYNTAX:                                                     #
# YYYY-MM-DD HH:MM:SS script-name|loglevel: the message                       #
#                                                                             #
# LOG LEVELS:                                                                 #
# error: a fatal fucking error                                                #
# warning: an error that is not immediately fatal                             #
# info: a normal operational message                                          #
# debug: a message that should only be used for testing and diagnostics       #
#                                                                             #
###############################################################################
# config for herbstluftwm

#        +----------------------------------------------------------+
#        |                     GLOBALS SECTION                      |
#        +----------------------------------------------------------+

# --| SOURCE |-----------------------------------------------------------------
# source container for more global variables
source "${HOME}/scripts/get-script-dir"
source "${XDG_CONFIG_HOME}/herbstluftwm/herbstluftwm-env"

# --| GLOBAL VARIABLES |-------------------------------------------------------
HLWM_AUTOSTART_DIR="$(dirname -- "$0")"
# HWLM_DIR=$(get_script_dir)

# --| LOGGING VARIABLES |------------------------------------------------------
# warning: lazy AF
SCRIPTNAME="herbstluftwm"
# timestamp format
TIMESTAMP="$(date +"%Y-%m-%d %H:%M:%S")"
# LOGLEVEL: decrease index with increasing severity
L3="${TIMESTAMP} ${SCRIPTNAME}|debug:"
L2="${TIMESTAMP} ${SCRIPTNAME}|info:"
# L1="${TIMESTAMP} ${SCRIPTNAME}|warning:"
# L0="${TIMESTAMP} ${SCRIPTNAME}|error:"

# send the entirety of autostart's execution to the log
exec 1>"${HERBSTLUFTWMLOG}" 3>&1
echo "---  herbstluftwm: running autostart script ---"
echo "${L2} LOGFILE is ${HERBSTLUFTWMLOG}"
echo "${L3} XDG_CONFIG_HOME is $XDG_CONFIG_HOME"

# print sourced variables
echo "${L3} HERBSTLUFTWMLOG is ${HERBSTLUFTWMLOG}"
echo "${L3} NOTIFICATIONDAEMONLOG is ${NOTIFICATIONDAEMONLOG}"
echo "${L3} STATUSBARLOG is ${STATUSBARLOG}"
echo "${L3} XRANDRLOG is ${XRANDRLOG}"
echo "${L3} KEYBINDMANAGERLOG is ${KEYBINDMANAGERLOG}"
echo "${L3} STATUSBARHEIGHT is ${STATUSBARHEIGHT}"
echo "${L3} HLWM_AUTOSTART_DIR is ${HLWM_AUTOSTART_DIR}"
# echo "${L3} SOURCE_DIR IS ${SOURCE_DIR}"

#        +----------------------------------------------------------+
#        |                     STARTUP SECTION                      |
#        +----------------------------------------------------------+

hc() {
  herbstclient "$@"
}

hc emit_hook reload

#        +----------------------------------------------------------+
#        |                     KEYBINDS SECTION                     |
#        +----------------------------------------------------------+

hc keyunbind --all # remove all existing keybindings

# --| MODIFIER SWAP |----------------------------------------------------------
# via running command: xmodmap
# xmodmap:  up to 4 keys per modifier, (keycodes in parentheses):
#
# mod1        Alt_L            (0x40),  Alt_R     (0x6c),  Alt_L   (0xcc),  Meta_L (0xcd)
# mod2        Num_Lock         (0x4d)
# mod3        ISO_Level5_Shift (0xcb)
# mod4        Super_L          (0x85),  Super_R   (0x86),  Super_L (0xce)
# mod5        ISO_Level3_Shift (0x5c)
# control     Control_L        (0x25),  Control_R (0x69)
# lock        Caps_Lock        (0x42)
# shift       Shift_L          (0x32),  Shift_R   (0x3e)
#
# xmodmap / herbstluftwm may report that Mod1 is an Unknown KeySym, but mod1 is
# not functional lol

Mod=Mod1 # Use alt as the main modifier

# --| MOUSE BINDS |------------------------------------------------------------
hc mouseunbind --all # remove all existing keybindings

hc mousebind "${Mod}"-Button1 move   # use mouse to move a client or frame
hc mousebind "${Mod}"-Button3 resize # resize frame as well

# --| WINDOW MANAGEMENT |-------------------------------------------------------
hc keybind "${Mod}"-Shift-q quit   # quit hlswm
hc keybind "${Mod}"-Shift-r reload # reload hlswm
hc keybind "${Mod}"-Shift-c close  # close focused window or frame

# --| CYCLE FOCUS |------------------------------------------------------------
hc keybind "${Mod}"-BackSpace cycle_monitor # cycle focus to next monitor
hc keybind "${Mod}"-Tab cycle_all +1        # cycle focus to next frame on same monitor; forward 1
hc keybind "${Mod}"-Shift-Tab cycle_all -1  # cycle focus to next frame on same monitor; backward 1
hc keybind "${Mod}"-c cycle                 # cycle focus to next client in the same frame

# --| MOVEMENT -- FOCUSED CLIENT |---------------------------------------------
# tiling and floating mode
hc keybind "${Mod}"-Left focus left
hc keybind "${Mod}"-Down focus down
hc keybind "${Mod}"-Up focus up
hc keybind "${Mod}"-Right focus right

# --| MOVEMENT -- CLIENTS |----------------------------------------------------
# moving clients between frames in tiling and floating mode
hc keybind "${Mod}"-Shift-Left shift left
hc keybind "${Mod}"-Shift-Down shift down
hc keybind "${Mod}"-Shift-Up shift up
hc keybind "${Mod}"-Shift-Right shift right

# --| FRAME SPLITTING |--------------------------------------------------------
# create an empty frame at location of focused monitor
hc keybind "${Mod}"-i split bottom 0.5 # split fovused frame vertically
hc keybind "${Mod}"-o split right 0.5  # split focused frame horizontally

hc keybind "${Mod}"-Control-space split explode # explode current frame into subframes

# --| RESIZING |---------------------------------------------------------------
# resizes frames and floating clients
resizestep=0.01
hc keybind "${Mod}"-Control-Up resize up +"${resizestep}"
hc keybind "${Mod}"-Control-Left resize left +"${resizestep}"
hc keybind "${Mod}"-Control-Down resize down +"${resizestep}"
hc keybind "${Mod}"-Control-Right resize right +"${resizestep}"

# --| LAYOUT |-----------------------------------------------------------------
hc keybind "${Mod}"-f floating toggle   # per focused FRAME
hc keybind "${Mod}"-l fullscreen toggle # per focused
hc keybind "${Mod}"-t pseudotile toggle # per focused
hc keybind "${Mod}"-r remove            # removes frame, merges contents with neighboring; per focused# per focused CLIENT

hc keybind "${Mod}"-Shift-f set_attr clients.focus.floating toggle  # toggle floating on focused CLIENT
hc keybind "${Mod}"-Shift-d set_attr clients.focus.decorated toggle # toggle decorations on focused CLIENT

# toggle between grid and max tab layout
hc keybind "${Mod}"-Ctrl-m spawn "${XDG_CONFIG_HOME}/herbstluftwm/scripts/maximize.sh"

# --| MINIMIZING |-------------------------------------------------------------
hc keybind "${Mod}"-Shift-m set_attr clients.focus.minimized true # minimizes focused window
hc keybind "${Mod}"-t pseudotile toggle                           # per focused
hc keybind "${Mod}"-r remove                                      # removes frame, merges contents with neighboring; per focused# per focused CLIENT

hc keybind "${Mod}"-Shift-f set_attr clients.focus.floating toggle  # toggle floating on focused CLIENT
hc keybind "${Mod}"-Shift-d set_attr clients.focus.decorated toggle # toggle decorations on focused CLIENT

# toggle between grid and max tab layout
hc keybind "${Mod}"-Ctrl-m spawn "${XDG_CONFIG_HOME}/herbstluftwm/scripts/maximize.sh"

# --| MINIMIZING |-------------------------------------------------------------
hc keybind "${Mod}"-Shift-m set_attr clients.focus.minimized true # minimizes focused window
hc keybind "${Mod}"-Control-m jumpto last-minimized               # jump to minimized windows sequentially and unminimize them

# unminimize all minimized clients on the current tag
hc keybind "${Mod}"-Ctrl-Shift-m substitute FOCUS "tags.focus.name" \
  foreach CLIENT clients. \
  sprintf MINATT "%c.minimized" CLIENT \
  sprintf TAGATT "%c.tag" CLIENT and \
  , compare MINATT "=" "true" \
  , compare TAGATT "=" FOCUS \
  , set_attr MINATT false
echo "${L3} set layout keybinds"

# --| LAYOUT SAVE & RECALL |---------------------------------------------------
# hc keybind "${Mod}"-Control-k        spawn $HOME/.config/herbstluftwm/scripts/save-layout.sh
# hc keybind "${Mod}"-Control-comma    spawn $HOME/.config/herbstluftwm/scripts/recall-layout.sh

###   LAYOUT SAVE & RECALL VIA DMENU   ###
# NOTE: BAR APPEARS AT TOP OF SCREEN
hc keybind "${Mod}"-Control-k spawn "${XDG_CONFIG_HOME}/herbstluftwm/scripts/herbstluftwm-save-tree.sh" save
hc keybind "${Mod}"-Control-comma spawn "${XDG_CONFIG_HOME}/herbstluftwm/scripts/herbstluftwm-save-tree.sh" load
echo "${L3} set layout save & recall via dmenu keybinds"

# --| SCREENSHOT SELECTION |---------------------------------------------------
hc keybind "${Mod}"-Shift-s spawn "${XDG_CONFIG_HOME}/herbstluftwm/scripts/screenshot.sh"
echo "${L3} set screenshot selection keybind"

#        +----------------------------------------------------------+
#        |                       TAGS SECTION                       |
#        +----------------------------------------------------------+

# --| monitor-agnostic tag lists |---------------------------------------------

tag_names=({0..3})
tag_keys=({1..3} 0)

hc silent rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}"; do
  hc add "${tag_names[$i]}"
  key="${tag_keys[$i]}"
  if [ -n "$key" ]; then
    hc keybind "$Mod-$key" use_index "$i"
    hc keybind "$Mod-Shift-$key" move_index "$i"
  fi
done
echo "${L3} set tag lists"

### CYCLING TAGS ###
hc keybind "${Mod}"-period use_index +1 --skip-visible
hc keybind "${Mod}"-comma use_index -1 --skip-visible
echo "${L3} set cycle tags keybinds"

# --| per-monitor tag lists |--------------------------------------------------

# # NOTE: consider naming these tags something cooler like "HMI-1" or "VUI-1" etc

# # define tag names
# monitor1_tags=(1) # tag names for monitor 1
# monitor2_tags=(2) # tag names for monitor 2
# monitor3_tags=(3) # tag names for monitor 3
# auxilliary_tags=({4..8}) # tag names for all other monitors
#
# # define tag keybinds
# tag_keys=({1..9} 0) # possible keys for use for tags
#
# # rename "default" tag to "monitor1_tags"; || return 1 if prior returns non-zero value
# hc rename default "${monitor1_tags[0]}" || true
# # for each tag pointed to by each monitor variable defined by above [@=all arguments]
# for tag in "${monitor1_tags[@]}" "${monitor2_tags[@]}" "${monitor3_tags[@]}" "${auxilliary_tags[@]}"; do
#   hc try silent add "${tag}"
# done
#
# for i in "${!tag_keys[@]}"; do
#   key="${tag_keys[${i}]}"
#   # the keybinding works as follows: the or executes the commands separated by
#   # CASE and stops executing them after the first of those succeeds.
#   # the first command is: check that we are on monitor 3 and can switch to tag "${monitor1_tags[$i]}"
#   # if only one of these two steps fail, try the second one (and so one).
#   # The setup for two monitors is as follows:
#   hc keybind "${Mod}-${key}" \
#     or \
#     CASE and . compare monitors.focus.index = 0 . use "${monitor1_tags[${i}]}" \
#     CASE and . compare monitors.focus.index = 1 . use "${monitor2_tags[${i}]}" \
#     CASE and . compare monitors.focus.index = 2 . use "${monitor3_tags[${i}]}" \
#     CASE use "${auxilliary_tags[${i}]}"
#   hc keybind "${Mod}-Shift-${key}" \
#     or \
#     CASE and . compare monitors.focus.index = 0 . move "${monitor1_tags[${i}]}" \
#     CASE and . compare monitors.focus.index = 1 . move "${monitor2_tags[${i}]}" \
#     CASE and . compare monitors.focus.index = 2 . move "${monitor3_tags[${i}]}" \
#     CASE move "${auxilliary_tags[${i}]}"
# done
#
# # cycle through tags: define cycle
# # add additional information in order to cycle only through a monitor's tags
# # and not through all tags
# define-tag-cycle() {
#   local n=$#
#   local tags=("$@")
#   for i in "${!tags[@]}"; do
#     local t="${tags[${i}]}"
#     hc chain , new_attr string tags.by-name."${t}".my_previous_tag \
#       , set_attr tags.by-name."${t}".my_previous_tag "${tags[$(((i - 1 + n) % n))]}" \
#       , new_attr string tags.by-name."${t}".my_next_tag \
#       , set_attr tags.by-name."${t}".my_next_tag "${tags[$(((i + 1) % n))]}"
#   done
# }
#
# define-tag-cycle "${monitor1_tags[@]}"
# define-tag-cycle "${monitor2_tags[@]}"
# define-tag-cycle "${monitor3_tags[@]}"
# define-tag-cycle "${auxilliary_tags[@]}"
#
# # cycle through tags: assign keybinds
# # check whether the current tag as a custom "next tag" configured
# # if yes, jump to that one, otherwise fall back to ordinary use_index +1
# hc keybind "${Mod}"-period or , substitute NEXT tags.focus.my_next_tag use NEXT \
#   , use_index +1 --skip-visible
# hc keybind "${Mod}"-comma or , substitute PREV tags.focus.my_previous_tag use PREV \
#   , use_index +1 --skip-visible

#        +----------------------------------------------------------+
#        |                      THEME SECTION                       |
#        +----------------------------------------------------------+

# #002B36 #586E75 #839496 #EEE8D5 #B58900 #DC322F #6C71C4 #2AA198 #B8D8D6
# #073642 #657B83 #93A1A1 #FDF6E3 #CB4B16 #D33682 #268bC2 #859900 #C5E7E5

hc set verbose false
hc set wmname herbstluftwm

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

# --| FRAME STYLE |------------------------------------------------------------
hc set frame_border_active_color '#CB4B16dd'
hc set frame_border_normal_color '#657B83cc'
hc set frame_bg_normal_color '#C5E7E5FF'
hc set frame_bg_active_color '#B8D8D6FF'
hc set frame_bg_transparent on
hc set frame_transparent_width 1
hc set frame_gap 4
hc set frame_padding 0
hc set frame_border_width 1
hc set show_frame_decorations 'nonempty'
#hc set tight_decorations         true

# --| WINDOW STYLE |-----------------------------------------------------------
hc set window_gap 1
hc set gapless_grid true
hc set smart_window_surroundings on
hc set smart_frame_surroundings on
hc set tabbed_max true
hc set mouse_recenter_gap 0

# --| TITLE BAR STYLE |--------------------------------------------------------
hc attr theme.title_height 14
hc attr theme.title_when 'one_tab'
hc attr theme.title_font 'Px437 Compaq Port3:pixelsize=12' # for XFT fonts
# hc attr theme.title_font '-*-fixed-medium-r-*-*-13-*-*-*-*-*-*-*' # for standard bitmap fonts
hc attr theme.title_depth 2 # space below the title's baseline
hc attr theme.active.color '#93A1A1'
hc attr theme.title_color '#002B36'
hc attr theme.normal.color '#FDF6E3dd'
hc attr theme.urgent.color '#CB4B16dd'
hc attr theme.tab_color '#EEE8D5dd'
hc attr theme.active.tab_color '#B8D8D6dd'
hc attr theme.active.tab_outer_color '#C5E7E5dd'
hc attr theme.active.tab_title_color '#002B36'
hc attr theme.normal.title_color '#657B83'
hc attr theme.inner_width 0
hc attr theme.inner_color '#93A1A1'
hc attr theme.border_width 1
hc attr theme.active.border_width 1
hc attr theme.floating.border_width 1
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color '#839496'
hc attr theme.active.inner_color '#CB4B16'
hc attr theme.urgent.inner_color '#D33682'
hc attr theme.normal.inner_color '#C5E7E5'
hc attr theme.background_color '#93A1A1bb'
hc attr theme.tiling.outer_width 1

# copy inner color to outer_color
for state in active urgent normal; do
  hc substitute C theme."${state}".inner_color attr theme."${state}".outer_color C
done

#        +----------------------------------------------------------+
#        |                      RULES SECTION                       |
#        +----------------------------------------------------------+

hc unrule -F

hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
hc rule fixedsize floating=on

# hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on floating=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc rule title='Font Forge' floating=on
hc rule title='Font Information.*' floating=on
hc rule title='Spectacle' floating=on
hc rule class='zenity' floating=on
hc rule class~'[Cc]onky' manage=off
hc rule class~'[Gg]alculator' floating=on
hc rule class='[Ss]pectacle' manage=off
hc rule class='[Ss]crot' manage=off

hc rule class=Keybindings floating=on
hc rule class=Music floating=on
hc rule class=Sysinfo floating=on
hc rule class~'[Gg]pick' floating=on

# hc rule instance=sys tag=1
# hc rule instance=work tag=2
# hc rule instance=com tag=3 floating=on
# hc rule instance=tj tag=3
# hc rule instance=komala tag=5
# hc rule instance=home tag=6
# hc rule instance=tj-laptop tag=6

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

#        +----------------------------------------------------------+
#        |                     MONITORS SECTION                     |
#        +----------------------------------------------------------+

# --| DEFINE MONITOR SIZES AND POSITIONS |-------------------------------------
# xrandr -q | grep " connected" | cut -d ' ' -f1
# hc list_monitors --no-disjoin

echo "${L2} initializing monitors..."

hc set_monitors 2560x1440+0+0 3440x1440+2560+0 2560x1440+6000+0

# hc pad <id> "top" "right" "bottom" "left"
hc pad 0 "0" "0" "0" "0"
hc pad 1 "0" "0" "${STATUSBARHEIGHT}" "0"
hc pad 2 "${STATUSBARHEIGHT}" "0" "${STATUSBARHEIGHT}" "0"

# output settings to log, in case display layout seems wrong
hc list_monitors --no-disjoin | while IFS= read -r line; do
  echo "${L2} $line"
done

# --| DEFINE BEHAVIOR |--------------------------------------------------------
hc set focus_crosses_monitor_boundaries 1
hc set swap_monitors_to_get_tag 0

#        +----------------------------------------------------------+
#        |              EXTERNAL APP AUTOSTART SECTION              |
#        +----------------------------------------------------------+

# "${XDG_CONFIG_HOME}/herbstluftwm/scripts/herbstluftwm-start.sh" --sxhkd &
# echo "${L2} starting sxhkd using herbstluftwm-start.sh --sxhkd"
# murder SXHKD processes
pkill -x sxhkd
# wait for all SXHKD processes to terminate
while pgrep -u "${UID}" -x sxhkd >/dev/null; do
  sleep 1
done
echo "${L2} sxhkd initiating..."
sleep 1
#start SXHKD config...
sxhkd -c "${HOME}/.config/herbstluftwm/sxhkdrc" &
dunstify "sxhkd" "reloading config ~/.config/herbstluftwm/sxhkdrc" &
echo "${L2} starting sxhkd using ${HOME}/.config/herbstluftwm/sxhkdrc"

dunstctl reload "${XDG_CONFIG_HOME}/herbstluftwm/dunstrc" &>"${NOTIFICATIONDAEMONLOG}" &
echo "${L2} reloading dunst using ${XDG_CONFIG_HOME}/herbstluftwm/dunstrc"

"${HOME}/.config/herbstluftwm/scripts/herbstluftwm-start.sh" --polybar &>"${STATUSBARLOG}" &
echo "${L2} starting polybar using herbstluftwm-start.sh --polybar"

xwallpaper --zoom "${HOME}/.local/share/wallpapers/LA-wallpapers/1_d10_p2_average.png" &
echo "${L2} setting xwallpaper  --zoom \"${HOME}/.local/share/wallpapers/LA-wallpapers/1_d10_p2_average.png\""

xrandr --dpi 122.38/DisplayPort-0 --dpi 109.68/DisplayPort-1 --dpi 96/DisplayPort-2 >"${XRANDRLOG}" &

"${XDG_CONFIG_HOME}/herbstluftwm/scripts/herbstluftwm-start.sh" --conky
echo "${L2} starting conky using herbstluftwm-start.sh --conky"

# need to prevent this from going into the herbstluftwm log
input-remapper-control --config-dir "${XDG_CONFIG_HOME}"/input-remapper-2/ --command autoload &>/dev/null
echo "${L2} setting input-remapper-control --config-dir ${XDG_CONFIG_HOME}/input-remapper-2/ --command autoload"

echo "---  herbstluftwm: end of autostart file ---"
