#!/usr/bin/env bash
#
# herbstluftwm setup's temporary environment variables

#***********************#
#   LOG FILES SECTION   #
#***********************#

export HERBSTLUFTWMLOG="${HOME}/LOGS/herbstluftwm.log"
export NOTIFICATIONDAEMONLOG="${HOME}/LOGS/herbstluftwm-dunst.log"
export STATUSBARLOG="${HOME}/LOGS/herbstluftwm-polybar.log"
export XRANDRLOG="${HOME}/LOGS/herbstluftwm-xrandr.log"
export KEYBINDMANAGERLOG="${HOME}/LOGS/herbstluftwm-sxhkd.log"

#******************************#
#   SECTION GLOBAL VARIABLES   #
#******************************#

export STATUSBARHEIGHT=20

# split to avoid masking return values
SCREENSHOTDATE="$(date +%s)"
export SCREENSHOTOUTPUT="${HOME}"/Pictures/herbstluftwm_screenshots/screenshot"${SCREENSHOTDATE}".png

