#!/usr/bin/env bash
#
# herbstluftwm setup's temporary environment variables
# usage:
# source "${XDG_CONFIG_HOME}/herbstluftwm/herbstluftwm-env"

# --| source xprofile |--------------------------------------------------------
source "${HOME}"/.xprofile
source "${HOME}"/.bashrc

# --| LOG FILES |--------------------------------------------------------------
# shellcheck disable=SC2154 
LOG_DESKTOPENV_DIR="${HOME}"/logs/desktop-env
HERBSTLUFTWMENVLOG="${LOG_DESKTOPENV_DIR}"/herbstluftwm-env.log

export CONKYLOG="${LOG_DESKTOPENV_DIR}"/herbstluftwm-conky.log
export HERBSTLUFTWMLOG="${LOG_DESKTOPENV_DIR}"/herbstluftwm.log
export HERBSTCLIENTLOG="${LOG_DESKTOPENV_DIR}"/herbstclient.log
export KEYBINDMANAGERLOG="${LOG_DESKTOPENV_DIR}"/herbstluftwm-sxhkd.log
export NOTIFICATIONDAEMONLOG="${LOG_DESKTOPENV_DIR}"/herbstluftwm-dunst.log
export STATUSBARLOG="${LOG_DESKTOPENV_DIR}"/herbstluftwm-polybar.log
export XRANDRLOG="${LOG_DESKTOPENV_DIR}"/herbstluftwm-xrandr.log

# --| GLOBAL VARIABLES |-------------------------------------------------------
export STATUSBARHEIGHT=20

# --| LOGGING VARIABLES |------------------------------------------------------
# warning: lazy AF
LOGFILE="${HERBSTLUFTWMENVLOG}"
SCRIPTNAME="herbstluftwm-env"
# timestamp format
TIMESTAMP="$(date +"%Y-%m-%d %H:%M:%S")"
# LOGLEVEL: decrease index with increasing severity
L3="${TIMESTAMP} ${SCRIPTNAME}|debug:"
# L2="${TIMESTAMP} ${SCRIPTNAME}|info:"
# L1="${TIMESTAMP} ${SCRIPTNAME}|warning:"
# L0="${TIMESTAMP} ${SCRIPTNAME}|error:"

touch "${HERBSTLUFTWMENVLOG}"

{
  echo "${L3} HOME is $HOME."
  # shellcheck disable=SC2154
  echo "${L3} XDG_CONFIG_HOME is $XDG_CONFIG_HOME."
  echo "${L3} HERBSTLUFTWMENVLOG is $HERBSTLUFTWMENVLOG."
  echo "${L3} LOGFILE path is $LOGFILE."

  echo "${L3} SCREENSHOTOUTPUT is $SCREENSHOTOUTPUT."
  echo "${L3} HERBSTLUFTWMLOG is $HERBSTLUFTWMLOG."
  echo "${L3} CONKYLOG is $CONKYLOG."
  echo "${L3} HERBSTLUFTWMLOG is $HERBSTLUFTWMLOG."
  echo "${L3} KEYBINDMANAGERLOG is $KEYBINDMANAGERLOG."
  echo "${L3} NOTIFICATIONDAEMONLOG is $NOTIFICATIONDAEMONLOG."
  echo "${L3} STATUSBARLOG is $STATUSBARLOG."
  echo "${L3} XRANDRLOG is $XRANDRLOG."

  echo "${L3} STATUSBARHEIGHT is $STATUSBARHEIGHT."
} >"$LOGFILE"

# --| CREATE LOG FILES |-------------------------------------------------------
touch "${HERBSTLUFTWMLOG}"
touch "${HERBSTCLIENTLOG}"
touch "${NOTIFICATIONDAEMONLOG}"
touch "${STATUSBARLOG}"
touch "${XRANDRLOG}"
touch "${KEYBINDMANAGERLOG}"
touch "${CONKYLOG}"
